### ISSUE TITLE
Question for some simple DID queries

### ISSUE THREAD

**Issue by milhead2** [htkim40/Shiba_DoIP_Tool#4]
Hi, 

I've been using your tool to rough out some DoIP interface work to reflash an ECU we are working on.  I'm also looking to write a script that will query/set a couple DID's 

Do you have an example script that will do something simple like read and write a VIN (0xF190).

Thanks!

**Comment by rbogs** [comment]
DoIPReadDID and DoIPWriteDID can be used to read / write VIN or any other DIDs.
